name: Deploy to Local Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ${{ github.workspace }}
          ./scripts/deploy.sh
